# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fuel My Wanderlust
description: > # this means to ignore newlines until "baseurl:"
  A travel inspiration website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fuelmywanderlust.com" # the base hostname & protocol for your site
twitter_username: hanna__taylor
github_username:  hannataylor
linkedin_username: hannataylor
instagram_username: hanna__taylor

# Build settings
markdown: kramdown

# Handling Reading
include: ['_pages']